---
- hosts: broker_collectors_and_payouts,aggr_collectors,broker_match,aggr_match,aggr_web_api
  gather_facts: no
  remote_user: root
  vars:
    node_bin_path: PATH="/root/.nvm/versions/node/v16.13.1/bin:$PATH"
  tasks:
    - name: yarn install
      shell:
        chdir: /root/ctoker
        cmd: "{{ node_bin_path }} yarn"

- hosts: broker_collectors_and_payouts,broker_match
  gather_facts: no
  remote_user: root
  vars:
    node_bin_path: PATH="/root/.nvm/versions/node/v16.13.1/bin:$PATH"
  tasks:
    - name: build broker
      shell:
        chdir: /root/ctoker
        cmd: "{{ node_bin_path }} yarn workspace @ctocker/lib build && {{ node_bin_path }} yarn workspace @ctocker/broker build"

- hosts: aggr_collectors,aggr_match
  gather_facts: no
  remote_user: root
  vars:
    node_bin_path: PATH="/root/.nvm/versions/node/v16.13.1/bin:$PATH"
  tasks:
    - name: build aggr
      shell:
        chdir: /root/ctoker
        cmd: "{{ node_bin_path }} yarn workspace @ctocker/lib build && {{ node_bin_path }} yarn workspace @ctocker/ctocks build"

- hosts: aggr_web_api
  gather_facts: no
  remote_user: root
  vars:
    node_bin_path: PATH="/root/.nvm/versions/node/v16.13.1/bin:$PATH"
  tasks:
    - name: build web api
      shell:
        chdir: /root/ctoker
        cmd: "{{ node_bin_path }} yarn workspace @ctocker/lib build && {{ node_bin_path }} yarn workspace @ctocker/web-api build"
