---
- hosts: ctoker-broker-xch
  gather_facts: no
  remote_user: root
  vars:
    node_bin_path: PATH="/root/.nvm/versions/node/v16.13.1/bin:$PATH"
  tasks:
    - name: Migrate broker
      shell:
        cmd: "{{node_bin_path}} yarn workspace @ctocker/broker migrate"
        chdir: /root/ctoker

- hosts: ctoker-aggr-xch
  gather_facts: no
  remote_user: root
  vars:
    node_bin_path: PATH="/root/.nvm/versions/node/v16.13.1/bin:$PATH"
  tasks:
    - name: Migrate ctocks
      shell:
        cmd: "{{node_bin_path}} yarn workspace @ctocker/ctocks migrate"
        chdir: /root/ctoker
