---
- hosts: broker_collectors_and_payouts,aggr_collectors,aggr_web_api,broker_match,aggr_match
  gather_facts: no
  remote_user: root
  vars:
    node_bin_path: PATH="/root/.nvm/versions/node/v16.13.1/bin:$PATH"
  tasks:
    - name: Run via pm2
      shell:
        cmd: "{{node_bin_path}} pm2 start process.config.js"
        chdir: /root/ctoker
